### ISSUE TITLE
Show basic error report

### ISSUE THREAD

**Issue by karthikc** [karthikc/binge-v1#5]
Show list of all rows with errors as a table. Each row should:
1. Show the row number
2. Show all cells
3. Show cells with errors highlighted in red
4. Error cells should show validation messages on hover.

**Comment by nitinstp23** [comment]
Created branch: https://github.com/karthikc/binge/tree/show_basic_error_report

Added these commits: 
  1) e05fd89ca6746b762ced7358d0e8db87c4a9c567
  2) 6856e86f1e5fd8cb852147130ffd0f54f8a2de96
  3) 5167ed4552a9955ec6d42437e7f24b53f9ca8088

Need to add more integration tests before closing. :+1:

**Comment by nitinstp23** [comment]
Added integration tests - https://github.com/karthikc/binge/commit/da23cdf8f111714137fd7297d82139f86009ff27
